In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv('onlinefoods.csv')

In [ ]:
df

Age  Gender Marital Status Occupation  Monthly Income  \
0     20  Female         Single    Student       No Income   
1     24  Female         Single    Student  Below Rs.10000   
2     22    Male         Single    Student  Below Rs.10000   
3     22  Female         Single    Student       No Income   
4     22    Male         Single    Student  Below Rs.10000   
..   ...     ...            ...        ...             ...   
383   23  Female         Single    Student       No Income   
384   23  Female         Single    Student       No Income   
385   22  Female         Single    Student       No Income   
386   23    Male         Single    Student  Below Rs.10000   
387   23    Male         Single    Student       No Income   

    Educational Qualifications  Family size  latitude  longitude  Pin code  \
0                Post Graduate            4   12.9766    77.5993    560001   
1                     Graduate            3   12.9770    77.5773    560009   
2                Post Graduate            3   12.9551    77.6593    560017   
3                     Graduate            6   12.9473    77.5616    560019   
4                Post Graduate            4   12.9850    77.5533    560010   
..                         ...          ...       ...        ...       ...   
383              Post Graduate            2   12.9766    77.5993    560001   
384              Post Graduate            4   12.9854    77.7081    560048   
385              Post Graduate            5   12.9850    77.5533    560010   
386              Post Graduate            2   12.9770    77.5773    560009   
387              Post Graduate            5   12.8988    77.5764    560078   

    Output   Feedback Unnamed: 12  
0      Yes   Positive         Yes  
1      Yes   Positive         Yes  
2      Yes  Negative          Yes  
3      Yes   Positive         Yes  
4      Yes   Positive         Yes  
..     ...        ...         ...  
383    Yes   Positive         Yes  
384    Yes   Positive         Yes  
385    Yes   Positive         Yes  
386    Yes   Positive         Yes  
387    Yes   Positive         Yes  

[388 rows x 13 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         388 non-null    int64  
 1   Gender                      388 non-null    object 
 2   Marital Status              388 non-null    object 
 3   Occupation                  388 non-null    object 
 4   Monthly Income              388 non-null    object 
 5   Educational Qualifications  388 non-null    object 
 6   Family size                 388 non-null    int64  
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64  
 10  Output                      388 non-null    object 
 11  Feedback                    388 non-null    object 
 12  Unnamed: 12                 388 non-null    object 
dtypes: float64(2), int64(3), object(8)


In [ ]:
df.drop(df.columns[-1], axis=1, inplace= True)
df

Age  Gender Marital Status Occupation  Monthly Income  \
0     20  Female         Single    Student       No Income   
1     24  Female         Single    Student  Below Rs.10000   
2     22    Male         Single    Student  Below Rs.10000   
3     22  Female         Single    Student       No Income   
4     22    Male         Single    Student  Below Rs.10000   
..   ...     ...            ...        ...             ...   
383   23  Female         Single    Student       No Income   
384   23  Female         Single    Student       No Income   
385   22  Female         Single    Student       No Income   
386   23    Male         Single    Student  Below Rs.10000   
387   23    Male         Single    Student       No Income   

    Educational Qualifications  Family size  latitude  longitude  Pin code  \
0                Post Graduate            4   12.9766    77.5993    560001   
1                     Graduate            3   12.9770    77.5773    560009   
2                Post Graduate            3   12.9551    77.6593    560017   
3                     Graduate            6   12.9473    77.5616    560019   
4                Post Graduate            4   12.9850    77.5533    560010   
..                         ...          ...       ...        ...       ...   
383              Post Graduate            2   12.9766    77.5993    560001   
384              Post Graduate            4   12.9854    77.7081    560048   
385              Post Graduate            5   12.9850    77.5533    560010   
386              Post Graduate            2   12.9770    77.5773    560009   
387              Post Graduate            5   12.8988    77.5764    560078   

    Output   Feedback  
0      Yes   Positive  
1      Yes   Positive  
2      Yes  Negative   
3      Yes   Positive  
4      Yes   Positive  
..     ...        ...  
383    Yes   Positive  
384    Yes   Positive  
385    Yes   Positive  
386    Yes   Positive  
387    Yes   Positive  

[388 rows x 12 columns]

In [ ]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
df['Marital Status'].unique()

array(['Single', 'Married', 'Prefer not to say'], dtype=object)

In [ ]:
df['Occupation'].unique()

array(['Student', 'Employee', 'Self Employeed', 'House wife'],
      dtype=object)

In [ ]:
df['Monthly Income'].unique()

array(['No Income', 'Below Rs.10000', 'More than 50000', '10001 to 25000',
       '25001 to 50000'], dtype=object)

In [ ]:
df['Educational Qualifications'].unique()

array(['Post Graduate', 'Graduate', 'Ph.D', 'Uneducated', 'School'],
      dtype=object)

In [ ]:
df['Output'].unique()

array(['Yes', 'No'], dtype=object)

#Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df[['Gender','Output','Feedback']]= df[['Gender','Output','Feedback']].apply(LabelEncoder().fit_transform)
df

Age  Gender Marital Status Occupation  Monthly Income  \
0     20       0         Single    Student       No Income   
1     24       0         Single    Student  Below Rs.10000   
2     22       1         Single    Student  Below Rs.10000   
3     22       0         Single    Student       No Income   
4     22       1         Single    Student  Below Rs.10000   
..   ...     ...            ...        ...             ...   
383   23       0         Single    Student       No Income   
384   23       0         Single    Student       No Income   
385   22       0         Single    Student       No Income   
386   23       1         Single    Student  Below Rs.10000   
387   23       1         Single    Student       No Income   

    Educational Qualifications  Family size  latitude  longitude  Pin code  \
0                Post Graduate            4   12.9766    77.5993    560001   
1                     Graduate            3   12.9770    77.5773    560009   
2                Post Graduate            3   12.9551    77.6593    560017   
3                     Graduate            6   12.9473    77.5616    560019   
4                Post Graduate            4   12.9850    77.5533    560010   
..                         ...          ...       ...        ...       ...   
383              Post Graduate            2   12.9766    77.5993    560001   
384              Post Graduate            4   12.9854    77.7081    560048   
385              Post Graduate            5   12.9850    77.5533    560010   
386              Post Graduate            2   12.9770    77.5773    560009   
387              Post Graduate            5   12.8988    77.5764    560078   

     Output  Feedback  
0         1         1  
1         1         1  
2         1         0  
3         1         1  
4         1         1  
..      ...       ...  
383       1         1  
384       1         1  
385       1         1  
386       1         1  
387       1         1  

[388 rows x 12 columns]

#Setting Target Variables & Features

In [ ]:
X= df.iloc[:,:-1].values
y= df.iloc[:,-1].values

In [ ]:
X

array([[20, 0, 'Single', ..., 77.5993, 560001, 1],
       [24, 0, 'Single', ..., 77.5773, 560009, 1],
       [22, 1, 'Single', ..., 77.6593, 560017, 1],
       ...,
       [22, 0, 'Single', ..., 77.5533, 560010, 1],
       [23, 1, 'Single', ..., 77.5773, 560009, 1],
       [23, 1, 'Single', ..., 77.5764, 560078, 1]], dtype=object)

In [ ]:
y

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,

#One Hot Encoding

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[2,3,4,5])],remainder='passthrough')
X= np.array(ct.fit_transform(X))

#Splitting Dataset into Training Set & Testing Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
X_train[: 5]

array([[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 28, 0, 5, 12.9757, 77.5586, 560023, 0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 22, 0, 1, 12.8845, 77.6036, 560076, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 23, 0, 2, 12.9766, 77.5993, 560001, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 21, 0, 3, 12.9149, 77.5635, 560070, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 19, 0, 4, 12.9537, 77.6176, 560047, 1]],
      dtype=object)

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [ ]:
X_train[0:5]

array([[ 1.61389317, -0.15199444, -1.52752523,  1.55131989, -0.15199444,
        -0.39587425, -1.10194633, -0.35675303,  2.20205736, -0.26956328,
        -0.43852901, -0.9745181 ,  1.08066284, -0.26956328, -0.88408664,
        -0.16275769, -0.0805823 ,  1.1377725 , -1.1612428 ,  1.31092677,
         0.0730299 , -0.80845468, -0.50872961, -1.86889101],
       [-0.6196197 , -0.15199444,  0.65465367, -0.64461238, -0.15199444,
        -0.39587425,  0.90748521, -0.35675303, -0.45412078, -0.26956328,
        -0.43852901,  1.0261482 , -0.925358  , -0.26956328,  1.13111085,
        -0.16275769, -0.0805823 , -0.86625861, -1.1612428 , -1.69934952,
        -1.95695858,  0.10155587,  1.2040629 ,  0.53507668],
       [-0.6196197 , -0.15199444,  0.65465367, -0.64461238, -0.15199444,
        -0.39587425,  0.90748521, -0.35675303, -0.45412078, -0.26956328,
        -0.43852901,  1.0261482 , -0.925358  , -0.26956328,  1.13111085,
        -0.16275769, -0.0805823 , -0.53225343, -1.1612428 , -0.94678044,
  

In [ ]:
X_test

array([[-0.6196197 , -0.15199444,  0.65465367, ..., -1.11583603,
         1.49491446,  0.53507668],
       [ 1.61389317, -0.15199444, -1.52752523, ..., -0.33322695,
        -1.18738324, -1.86889101],
       [-0.6196197 ,  6.57918797, -1.52752523, ..., -0.4950066 ,
        -0.60568013, -1.86889101],
       ...,
       [-0.6196197 , -0.15199444,  0.65465367, ...,  3.06212356,
         0.88089451, -1.86889101],
       [-0.6196197 , -0.15199444,  0.65465367, ...,  1.4706162 ,
         1.75344918,  0.53507668],
       [-0.6196197 , -0.15199444,  0.65465367, ..., -1.00056802,
         1.97966706,  0.53507668]])

#Training Logistic Regression Model on Training Set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

#Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[0,0,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,21,0,5,12.9770,	77.5773,	560009]])))

[1]


#Predicting Test Set Results

In [ ]:
y_pred= classifier.predict(X_test)

In [ ]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1])

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

In [ ]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]]


#Making Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm= confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 9  5]
 [ 7 57]]


0.8461538461538461

#KNN model

In [ ]:
X

array([[0.0, 0.0, 1.0, ..., 77.5993, 560001, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.6593, 560017, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5533, 560010, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.5764, 560078, 1]], dtype=object)

In [ ]:
y

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,

#Splitting Dataset into Training & Testing Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.22, random_state = 0)

In [ ]:
X_train

array([[1.0, 0.0, 0.0, ..., 77.6529, 560075, 1],
       [0.0, 0.0, 1.0, ..., 77.6044, 560029, 1],
       [0.0, 0.0, 1.0, ..., 77.5931, 560092, 0],
       ...,
       [0.0, 1.0, 0.0, ..., 77.5877, 560006, 0],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 1.0, 0.0, ..., 77.6804, 560016, 1]], dtype=object)

In [ ]:
y_train

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
X_test

array([[0.0, 0.0, 1.0, ..., 77.5434, 560085, 1],
       [1.0, 0.0, 0.0, ..., 77.5821, 560002, 0],
       [0.0, 1.0, 0.0, ..., 77.5741, 560020, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 77.6407, 560095, 0],
       [1.0, 0.0, 0.0, ..., 77.6821, 560036, 1],
       [0.0, 0.0, 1.0, ..., 77.5533, 560010, 1]], dtype=object)

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[ 1.61097427, -0.1540416 , -1.52272168, ...,  1.09642984,
         1.17781002,  0.53395354],
       [-0.62074238, -0.1540416 ,  0.65671883, ...,  0.11930086,
        -0.30992746,  0.53395354],
       [-0.62074238, -0.1540416 ,  0.65671883, ..., -0.10836011,
         1.72762605, -1.87282212],
       ...,
       [-0.62074238,  6.49175301, -1.52272168, ..., -0.21715386,
        -1.0537962 , -1.87282212],
       [-0.62074238, -0.1540416 ,  0.65671883, ..., -0.42668254,
        -0.95676984,  0.53395354],
       [-0.62074238,  6.49175301, -1.52272168, ...,  1.65047204,
        -0.73037501,  0.53395354]])

In [ ]:
X_test

array([[-0.62074238, -0.1540416 ,  0.65671883, ..., -1.10966548,
         1.50123122,  0.53395354],
       [ 1.61097427, -0.1540416 , -1.52272168, ..., -0.329977  ,
        -1.18316468, -1.87282212],
       [-0.62074238,  6.49175301, -1.52272168, ..., -0.49115291,
        -0.60100653, -1.87282212],
       ...,
       [-0.62074238, -0.1540416 ,  0.65671883, ...,  0.85063657,
         1.82465241, -1.87282212],
       [ 1.61097427, -0.1540416 , -1.52272168, ...,  1.68472192,
        -0.08353263,  0.53395354],
       [-0.62074238, -0.1540416 ,  0.65671883, ..., -0.91021028,
        -0.92442773,  0.53395354]])

#Training KNN model on Training Dataset

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 13, metric = 'manhattan')
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=13)

#Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[0,0,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,21,0,5,12.9770,	77.5773,560009]])))

[1]


In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 5 10]
 [ 0 71]]


0.8837209302325582

#SVM Classifier Model

In [ ]:
X

array([[0.0, 0.0, 1.0, ..., 77.5993, 560001, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.6593, 560017, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5533, 560010, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.5764, 560078, 1]], dtype=object)

In [ ]:
y

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.24, random_state = 0)

In [ ]:
X_train

array([[1.0, 0.0, 0.0, ..., 77.6848, 560103, 1],
       [1.0, 0.0, 0.0, ..., 77.54, 560022, 0],
       [0.0, 0.0, 1.0, ..., 77.5987, 560051, 1],
       ...,
       [0.0, 1.0, 0.0, ..., 77.5877, 560006, 0],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 1.0, 0.0, ..., 77.6804, 560016, 1]], dtype=object)

In [ ]:
y_train

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
X_test

array([[0.0, 0.0, 1.0, ..., 77.5434, 560085, 1],
       [1.0, 0.0, 0.0, ..., 77.5821, 560002, 0],
       [0.0, 1.0, 0.0, ..., 77.5741, 560020, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.539, 560096, 1],
       [0.0, 0.0, 1.0, ..., 77.6407, 560095, 0]], dtype=object)

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[ 1.62161328e+00, -1.56173762e-01, -1.53000297e+00, ...,
         1.72920082e+00,  2.11591318e+00,  5.27504379e-01],
       [ 1.62161328e+00, -1.56173762e-01, -1.53000297e+00, ...,
        -1.17281025e+00, -5.25816738e-01, -1.89571886e+00],
       [-6.16669839e-01, -1.56173762e-01,  6.53593502e-01, ...,
         3.62655948e-03,  4.19987800e-01,  5.27504379e-01],
       ...,
       [-6.16669839e-01,  6.40312424e+00, -1.53000297e+00, ...,
        -2.16830083e-01, -1.04763993e+00, -1.89571886e+00],
       [-6.16669839e-01, -1.56173762e-01,  6.53593502e-01, ...,
        -4.25261817e-01, -9.49798082e-01,  5.27504379e-01],
       [-6.16669839e-01,  6.40312424e+00, -1.53000297e+00, ...,
         1.64101817e+00, -7.21500435e-01,  5.27504379e-01]])

In [ ]:
X_test

array([[-0.61666984, -0.15617376,  0.6535935 , ..., -1.10466911,
         1.52886208,  0.52750438],
       [ 1.62161328, -0.15617376, -1.53000297, ..., -0.32906256,
        -1.17809573, -1.89571886],
       [-0.61666984,  6.40312424, -1.53000297, ..., -0.48939466,
        -0.59104464, -1.89571886],
       ...,
       [-0.61666984, -0.15617376,  0.6535935 , ..., -0.42526182,
        -0.94979808,  0.52750438],
       [-0.61666984, -0.15617376,  0.6535935 , ..., -1.19285176,
         1.88761553,  0.52750438],
       [-0.61666984, -0.15617376,  0.6535935 , ...,  0.8453701 ,
         1.85500158, -1.89571886]])

#Training SVM classifier model on training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='poly', random_state=0)

#Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[0,0,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,21,0,5,12.9770,	77.5773,560009]])))

[1]


#Predicting Test set result


In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12  5]
 [ 2 75]]


0.925531914893617

#Naive Bayes

In [ ]:
X

array([[0.0, 0.0, 1.0, ..., 77.5993, 560001, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.6593, 560017, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5533, 560010, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.5764, 560078, 1]], dtype=object)

In [ ]:
y

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 0)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, ..., 77.6408, 560038, 1],
       [0.0, 0.0, 1.0, ..., 77.5713, 560003, 1],
       [0.0, 0.0, 1.0, ..., 77.5635, 560070, 1],
       ...,
       [0.0, 1.0, 0.0, ..., 77.5877, 560006, 0],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 1.0, 0.0, ..., 77.6804, 560016, 1]], dtype=object)

In [ ]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,

In [ ]:
X_test

array([[0.0, 0.0, 1.0, ..., 77.5434, 560085, 1],
       [1.0, 0.0, 0.0, ..., 77.5821, 560002, 0],
       [0.0, 1.0, 0.0, ..., 77.5741, 560020, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5877, 560006, 0],
       [0.0, 0.0, 1.0, ..., 77.6131, 560042, 1],
       [1.0, 0.0, 0.0, ..., 77.7582, 560067, 0]], dtype=object)

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.63245553, -0.15786741,  0.67032769, ...,  0.82713006,
        -0.04162701,  0.53400023],
       [-0.63245553, -0.15786741,  0.67032769, ..., -0.55295914,
        -1.16419144,  0.53400023],
       [-0.63245553, -0.15786741,  0.67032769, ..., -0.70784685,
         0.98471761,  0.53400023],
       ...,
       [-0.63245553,  6.33442973, -1.49180769, ..., -0.2272978 ,
        -1.06797163, -1.87265836],
       [-0.63245553, -0.15786741,  0.67032769, ..., -0.43381475,
        -0.97175182,  0.53400023],
       [-0.63245553,  6.33442973, -1.49180769, ...,  1.61348304,
        -0.74723894,  0.53400023]])

In [ ]:
X_test

array([[-0.63245553, -0.15786741,  0.67032769, ..., -1.10698056,
         1.46581665,  0.53400023],
       [ 1.58113883, -0.15786741, -1.49180769, ..., -0.33849923,
        -1.19626471, -1.87265836],
       [-0.63245553,  6.33442973, -1.49180769, ..., -0.49735842,
        -0.61894586, -1.87265836],
       ...,
       [-0.63245553, -0.15786741,  0.67032769, ..., -0.2272978 ,
        -1.06797163, -1.87265836],
       [-0.63245553, -0.15786741,  0.67032769, ...,  0.27708012,
         0.08666607,  0.53400023],
       [ 1.58113883, -0.15786741, -1.49180769, ...,  3.15838864,
         0.8884978 , -1.87265836]])

#Training Naive Bayes Classification model

##Gaussian NB

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

#Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[0,0,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,21,0,5,12.9770,	77.5773,560009]])))

[0]


#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  1]
 [45  2]]


0.22033898305084745

#Bernoulli NB

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.12, random_state = 0)

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Training BernoulliNB model

In [ ]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

#Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[0,0,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,21,0,5,12.9770,	77.5773,560009]])))

[1]


In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  1]
 [ 5 35]]


0.8723404255319149

#Decision Tree Classifier

In [ ]:
X

array([[0.0, 0.0, 1.0, ..., 77.5993, 560001, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.6593, 560017, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5533, 560010, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.5764, 560078, 1]], dtype=object)

In [ ]:
y

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.12, random_state = 0)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, ..., 77.539, 560096, 1],
       [1.0, 0.0, 0.0, ..., 77.6131, 560042, 0],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       ...,
       [0.0, 1.0, 0.0, ..., 77.5877, 560006, 0],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 1.0, 0.0, ..., 77.6804, 560016, 1]], dtype=object)

In [ ]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,

In [ ]:
X_test

array([[0.0, 0.0, 1.0, ..., 77.5434, 560085, 1],
       [1.0, 0.0, 0.0, ..., 77.5821, 560002, 0],
       [0.0, 1.0, 0.0, ..., 77.5741, 560020, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5585, 560050, 1],
       [1.0, 0.0, 0.0, ..., 77.6221, 560034, 1],
       [0.0, 0.0, 1.0, ..., 77.5995, 560046, 1]], dtype=object)

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.6350529 , -0.16464639,  0.67621369, ..., -1.17843123,
         1.79847458,  0.5445897 ],
       [ 1.57467198, -0.16464639, -1.47882247, ...,  0.27087486,
         0.07640548, -1.83624477],
       [-0.6350529 , -0.16464639,  0.67621369, ..., -0.42932971,
        -0.97597009,  0.5445897 ],
       ...,
       [-0.6350529 ,  6.07362239, -1.47882247, ..., -0.22591833,
        -1.07164059, -1.83624477],
       [-0.6350529 , -0.16464639,  0.67621369, ..., -0.42932971,
        -0.97597009,  0.5445897 ],
       [-0.6350529 ,  6.07362239, -1.47882247, ...,  1.5871812 ,
        -0.75273891,  0.5445897 ]])

In [ ]:
X_test

array([[-6.35052896e-01, -1.64646390e-01,  6.76213692e-01, ...,
        -1.09237257e+00,  1.44768273e+00,  5.44589705e-01],
       [ 1.57467198e+00, -1.64646390e-01, -1.47882247e+00, ...,
        -3.35447530e-01, -1.19920127e+00, -1.83624477e+00],
       [-6.35052896e-01,  6.07362239e+00, -1.47882247e+00, ...,
        -4.91917824e-01, -6.25178233e-01, -1.83624477e+00],
       ...,
       [-6.35052896e-01, -1.64646390e-01,  6.76213692e-01, ...,
        -7.97034895e-01,  3.31526826e-01,  5.44589705e-01],
       [ 1.57467198e+00, -1.64646390e-01, -1.47882247e+00, ...,
         4.46903936e-01, -1.78715872e-01,  5.44589705e-01],
       [-6.35052896e-01, -1.64646390e-01,  6.76213692e-01, ...,
         4.87535737e-03,  2.03966152e-01,  5.44589705e-01]])

#Training Decision Tree Classification model

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

#Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[0,0,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,21,0,5,12.9770,	77.5773,560009]])))

[1]


#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  1]
 [ 4 36]]


0.8936170212765957

#Random Forest Classifier

In [ ]:
X

array([[0.0, 0.0, 1.0, ..., 77.5993, 560001, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.6593, 560017, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 77.5533, 560010, 1],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.5764, 560078, 1]], dtype=object)

In [ ]:
y

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 0.0, 1.0, ..., 77.75, 560066, 1],
       [0.0, 0.0, 1.0, ..., 77.5764, 560078, 1],
       ...,
       [0.0, 1.0, 0.0, ..., 77.5877, 560006, 0],
       [0.0, 0.0, 1.0, ..., 77.5773, 560009, 1],
       [0.0, 1.0, 0.0, ..., 77.6804, 560016, 1]], dtype=object)

In [ ]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
X_test

array([[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 22, 1, 3, 12.9306, 77.5434, 560085, 1],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 24, 1, 6, 12.9635, 77.5821, 560002, 0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 23, 0, 3, 12.9889, 77.5741, 560020, 0],
       [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 23, 0, 6, 12.9551, 77.6593, 560017, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 23, 1, 4, 13.0103, 77.5796, 560080, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 23, 1, 3, 13.0223, 77.7132, 560049, 1],
       [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 27, 0, 2, 12.9299, 77.6848, 560103, 1],
       [0.0, 

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.62928531, -0.16269784,  0.6694272 , ..., -0.43305224,
        -0.98237692,  0.53649127],
       [-0.62928531, -0.16269784,  0.6694272 , ...,  2.91925377,
         0.84521347,  0.53649127],
       [-0.62928531, -0.16269784,  0.6694272 , ..., -0.45052228,
         1.22996935,  0.53649127],
       ...,
       [-0.62928531,  6.14636297, -1.49381441, ..., -0.23117626,
        -1.07856589, -1.86396324],
       [-0.62928531, -0.16269784,  0.6694272 , ..., -0.43305224,
        -0.98237692,  0.53649127],
       [-0.62928531,  6.14636297, -1.49381441, ...,  1.56823757,
        -0.757936  ,  0.53649127]])

In [ ]:
X_test

array([[-6.29285309e-01, -1.62697843e-01,  6.69427203e-01,
        -6.64942674e-01, -1.43065846e-01, -3.89634677e-01,
         9.20087412e-01, -3.54692052e-01, -4.69339664e-01,
        -2.59380584e-01, -4.37179917e-01,  1.03203137e+00,
        -8.93850699e-01, -2.53030414e-01,  1.07439331e+00,
        -1.62697843e-01, -7.59189618e-02, -8.84527142e-01,
         8.73284755e-01, -2.05881236e-01, -9.16955679e-01,
        -1.09109031e+00,  1.45441027e+00,  5.36491266e-01],
       [ 1.58910432e+00, -1.62697843e-01, -1.49381441e+00,
        -6.64942674e-01, -1.43065846e-01,  2.56650668e+00,
        -1.08685326e+00, -3.54692052e-01, -4.69339664e-01,
        -2.59380584e-01,  2.28738778e+00, -9.68962790e-01,
        -8.93850699e-01,  3.95209408e+00, -9.30757842e-01,
        -1.62697843e-01, -7.59189618e-02, -2.11244759e-01,
         8.73284755e-01,  2.01636262e+00, -1.82437973e-01,
        -3.39878710e-01, -1.20681785e+00, -1.86396324e+00],
       [-6.29285309e-01,  6.14636297e+00, -1.49381441e

#Training Random Forest Classification model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

#Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[0,0,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,21,0,5,12.9770,	77.5773,560009]])))

[1]


#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  1]
 [ 1 31]]


0.9487179487179487

In [ ]:
my_dict= {
    "Logistic Regression": 0.8461538461538461,
    "KNN": 0.8837209302325582,
    "SVM": 0.925531914893617,
    "Naive Bayes (Gaussain)": 0.22033898305084745,
    "Naive Bayes (Bernoulli)": 0.8723404255319149 ,
    "Decision Tree": 0.8936170212765957,
    "Random Forest": 0.9487179487179487
}

In [ ]:
Series= pd.Series(my_dict)
Series

Logistic Regression        0.846154
KNN                        0.883721
SVM                        0.925532
Naive Bayes (Gaussain)     0.220339
Naive Bayes (Bernoulli)    0.872340
Decision Tree              0.893617
Random Forest              0.948718
dtype: float64